name: admet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - polaris
  - ipykernel
  - ipywidgets
  - umap-learn
  - pip
  - pip:
    - rdkit==2024.9.5
    - chembl_structure_pipeline==1.2.2
